from django.db import models

class Wine(models.Model):
    scope = models.IntegerField()
    style = models.CharField(max_length=50)
    label_color = models.CharField(max_length=50)
    country = models.CharField(max_length=50)
    region = models.CharField(max_length=50)
    appellation = models.CharField(max_length=50)
    grapes = models.CharField(max_length=50)
    vintage = models.IntegerField()
    producer = models.CharField(max_length=50)
    bottling = models.CharField(max_length=50)
    clarity = models.CharField(max_length=50)
    appearance_red = models.IntegerField()
    appearance_green = models.IntegerField()
    appearance_blue = models.IntegerField()
    appearance_other = models.CharField(max_length=50, null=True, blank=True)
    condition = models.CharField(max_length=50)
    nose_intensity = models.IntegerField()
    development = models.IntegerField()
    petillance = models.IntegerField()
    sweetness = models.IntegerField()
    acidity = models.IntegerField()
    alcohol = models.IntegerField()
    body = models.IntegerField()
    tannin_or_bitterness = models.IntegerField()
    finish = models.IntegerField()
    fruit_color = models.IntegerField()
    fruit_family = models.IntegerField()
    fruit_ripeness = models.IntegerField()
    fruit_subcondition = models.IntegerField()
    floral = models.IntegerField()
    herbaceous = models.IntegerField()
    herbal = models.IntegerField()
    earth_organic = models.IntegerField()
    earth_inorganic = models.IntegerField()
    grape_spice = models.IntegerField()
    oak_aroma = models.IntegerField()
    oak_intensity = models.IntegerField()
    aroma_other = models.CharField(max_length=255, null=True, blank=True)