# Generated by Django 4.2.3 on 2023-07-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.IntegerField()),
                ('style', models.CharField(max_length=50)),
                ('label_color', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=50)),
                ('appellation', models.CharField(max_length=50)),
                ('grapes', models.CharField(max_length=50)),
                ('vintage', models.IntegerField()),
                ('producer', models.CharField(max_length=50)),
                ('bottling', models.CharField(max_length=50)),
                ('clarity', models.CharField(max_length=50)),
                ('appearance_red', models.IntegerField()),
                ('appearance_green', models.IntegerField()),
                ('appearance_blue', models.IntegerField()),
                ('appearance_other', models.CharField(blank=True, max_length=50, null=True)),
                ('condition', models.CharField(max_length=50)),
                ('nose_intensity', models.IntegerField()),
                ('development', models.IntegerField()),
                ('petillance', models.IntegerField()),
                ('sweetness', models.IntegerField()),
                ('acidity', models.IntegerField()),
                ('alcohol', models.IntegerField()),
                ('body', models.IntegerField()),
                ('tannin_or_bitterness', models.IntegerField()),
                ('finish', models.IntegerField()),
                ('fruit_color', models.IntegerField()),
                ('fruit_family', models.IntegerField()),
                ('fruit_ripeness', models.IntegerField()),
                ('fruit_subcondition', models.IntegerField()),
                ('floral', models.IntegerField()),
                ('herbaceous', models.IntegerField()),
                ('herbal', models.IntegerField()),
                ('earth_organic', models.IntegerField()),
                ('earth_inorganic', models.IntegerField()),
                ('grape_spice', models.IntegerField()),
                ('oak_aroma', models.IntegerField()),
                ('oak_intensity', models.IntegerField()),
                ('aroma_other', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
