# Generated by Django 4.2.3 on 2023-07-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grape', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('appellation', models.CharField(max_length=100)),
                ('vintage', models.IntegerField()),
            ],
        ),
    ]
