# Generated by Django 4.2.3 on 2023-07-13 02:51

import django.core.validators
from django.db import migrations, models
import vinapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('vinapp', '0002_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='acidity',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='alcohol',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='appearance_blue',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='appearance_green',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='appearance_red',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='body',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='bottling',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='development',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='earth_inorganic',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='earth_organic',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='finish',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='floral',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='fruit_color',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='fruit_family',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='fruit_ripeness',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='fruit_subcondition',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='grape_spice',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='grapes',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wine',
            name='herbaceous',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='herbal',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wine',
            name='nose_intensity',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='oak_aroma',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='oak_intensity',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='petillance',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='producer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='wine',
            name='scope',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='wine',
            name='sweetness',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='tannin_or_bitterness',
            field=vinapp.models.StandardIntField(),
        ),
        migrations.AlterField(
            model_name='wine',
            name='vintage',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2023)]),
        ),
    ]
