# Generated by Django 4.2.3 on 2023-07-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vinapp', '0003_alter_wine_acidity_alter_wine_alcohol_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grape', models.BooleanField()),
                ('country', models.BooleanField()),
                ('region', models.BooleanField()),
                ('appellation', models.BooleanField()),
                ('vintage', models.BooleanField()),
                ('grape_score', models.IntegerField()),
                ('country_score', models.IntegerField()),
                ('region_score', models.IntegerField()),
                ('appellation_score', models.IntegerField()),
                ('vintage_score', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Answers',
            new_name='UserAnswers',
        ),
    ]
